version: "2"

networks:
  bio:
    external: true

services:
  bio-node:
    build: .
    container_name: bio-node
    volumes:
      - ./:/usr/www/app
    working_dir: /usr/www/app
    command: sh -c "pnpm i && pnpm run dev"
    ports:
      - 8086:8080
    networks:
      - bio
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 8G
